### ISSUE TITLE
Plugin doesn't mark the correct season as watched for Anime with more than 1 Season

### ISSUE THREAD

**Issue by DevYukine** [jellyfin/jellyfin-plugin-simkl#23]
I'm currently having issues with the Simkl plugin marking the wrong season episode as watched, this happens mostly for Anime right now.

Example Anime where i have this issues are `The Eminence in Shadow` or `The Ancient Magus' Bride`.

When i watch an Episode of S2 of each show, it will once finished mark the correct episode but for the wrong season as watched on Simkl.

I mainly use the TVDB Metadata downloader for the Library if that makes any difference, the shows metadata seems to also be fine and indicate that its an episode of S2.

![The Eminence in Shadow](https://github.com/jellyfin/jellyfin-plugin-simkl/assets/20647088/036a4ffa-e566-4eb9-8f13-0c07e3e49dc4)

![The Ancient Magus' Bride](https://github.com/jellyfin/jellyfin-plugin-simkl/assets/20647088/079a455e-4a72-4b85-87bd-173e01f38185)

**Comment by ekleop** [comment]
this matter was resolved here #25 
- you can copy the dll from here https://github.com/jellyfin/jellyfin-plugin-simkl/issues/24#issuecomment-1788133553
or wait until the push request will be merged. 
- ddd AniDB metadata as additional source and it should be fine.

**Comment by DevYukine** [comment]
@ekleop I sadly still seem to have this issue even tho i'm running the latest Version (V4.0.0.0) which includes that mentioned fix, i also have the AniDB metadata provider enabled as additional source.

Do i have to do anything else? i still get the exact same issue for Jujutsu Kaisen S2 as example
